// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQU6gjfbL_tZ2EskRgmvX9jrZvePM6gWM',
    appId: '1:751316971533:web:9e27593a36c03705a5e544',
    messagingSenderId: '751316971533',
    projectId: 'push-85b71',
    authDomain: 'push-85b71.firebaseapp.com',
    storageBucket: 'push-85b71.appspot.com',
    measurementId: 'G-HDSVKXQGC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh1eW3RoP63Ctc80Ue-Nw5pKT-W569psw',
    appId: '1:751316971533:android:598ed8805080dcbda5e544',
    messagingSenderId: '751316971533',
    projectId: 'push-85b71',
    storageBucket: 'push-85b71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6rtEod5E093rDZ1qmMGTSDGJd_6PfhZU',
    appId: '1:751316971533:ios:c00d915758a6ac10a5e544',
    messagingSenderId: '751316971533',
    projectId: 'push-85b71',
    storageBucket: 'push-85b71.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6rtEod5E093rDZ1qmMGTSDGJd_6PfhZU',
    appId: '1:751316971533:ios:c00d915758a6ac10a5e544',
    messagingSenderId: '751316971533',
    projectId: 'push-85b71',
    storageBucket: 'push-85b71.appspot.com',
    iosBundleId: 'com.example.push',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQU6gjfbL_tZ2EskRgmvX9jrZvePM6gWM',
    appId: '1:751316971533:web:31848c6c5e0b7917a5e544',
    messagingSenderId: '751316971533',
    projectId: 'push-85b71',
    authDomain: 'push-85b71.firebaseapp.com',
    storageBucket: 'push-85b71.appspot.com',
    measurementId: 'G-XT1DYHE9GM',
  );
}
